# This workflow will run unit tests using Gradle when a Pull Request is opened against "main" branch

name: Gradle Unit Tests

on:
  pull_request:
      brances: [main]

jobs:
  build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Clean
        run: ./gradlew clean
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
