# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle and NPM Package

on:
  release:
      types: [created]

jobs:
  delete package:
      runs-on: ubuntu-latest
      steps:
        
      - uses: actions/delete-package-versions@v1
        with:
         owner: 'github'
         repo: 'packages'
         package-name: 'tech.ctawave.cmcd 0.0.1'
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github # value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      
      - name: Clean
        run: ./gradlew clean
      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      # The USERNAME and TOKEN need to correspond to the credentials environment variabls used in
      # the publishing section of your build.gradle
      - name: Publish Maven to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js #Publish NPM to GitHub Packages
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - name: Publish NPM to GitHub Packages
        run: npm run publish:npm

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm run publish:npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
